---
- hosts: bb-js  # hosts中指定
  remote_user: bb-js  # 如果和当前用户一样，则无需指定
  tasks:
    - name: check out bb-js.org
      git: dest=~/bb-js-env/bb-js.org repo=https://github.com/bb-js/bb-js.org
           update=yes
    - name: make virtualenv
      shell: 'virtualenv ~/bb-js-env'
    - name: install requirements
      pip: requirements=~/bb-js-env/bb-js.org/requirements.txt 
           virtualenv=~/bb-js-env
    - name: run server.py
      shell: . ./bin/activate && cd bb-js.org &&  supervisord -c conf/supervisord.conf chdir=~/bb-js-env
