---
- hosts: bb-js  # hosts中指定
  remote_user: bb-js  # 如果和当前用户一样，则无需指定
  tasks:
    - name: run server.py
      shell: . ./bin/activate && cd bb-js.org &&  supervisorctl -c conf/supervisord.conf restart all chdir=~/bb-js-env
